import { createFileRoute } from "@tanstack/react-router";
import { createProdAuthenticator } from "@/perimeter/betterAuthAuthenticator";

/**
 * DEV-ONLY identity resolution for `everyapp dev --mode mirror`.
 *
 * The CLI's gateway-lite runs the real perimeter locally but has no Better Auth
 * session of its own. In mirror mode it forwards the browser's session cookie
 * here; this endpoint resolves the REAL user + active organization and returns
 * the shape the perimeter's SessionAuthenticator needs. The CLI then mints the
 * (dev-kid) identity JWT for that real user.
 *
 * Gated to dev builds: `import.meta.env.DEV` is statically `false` in a
 * production `vite build`, so this handler 404s in the deployed gateway and is
 * tree-shaken to a stub. It is never a production attack surface.
 *
 * NOTE: per-app access enforcement (user_app_access) lands with the Phase-5
 * app-registration flow. Until then this returns `hasAccess: true` for any
 * authenticated user with an active org, so a developer can exercise their
 * in-development app with a real login. It is dev-only and unreachable in prod.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- route tree is
// regenerated by the TanStack plugin at dev/build time; cast until then.
export const Route = createFileRoute("/api/dev/identity" as any)({
  server: {
    handlers: {
      GET: async ({ request }) => {
        if (!import.meta.env.DEV) {
          return new Response("Not found", { status: 404 });
        }

        const session = await createProdAuthenticator().authenticate(request);

        if (!session) {
          return json({ session: null, reason: "no_session" });
        }

        return json({
          session,
          hasAccess: true,
          reason: null,
        });
      },
    },
  },
});

function json(body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: {
      "content-type": "application/json",
      "cache-control": "no-store",
    },
  });
}
