/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsBuildAnAppRouteImport } from './routes/docs/build-an-app'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogsSplatRouteImport } from './routes/blogs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBuildAnAppRoute = DocsBuildAnAppRouteImport.update({
  id: '/docs/build-an-app',
  path: '/docs/build-an-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSplatRoute = BlogsSplatRouteImport.update({
  id: '/blogs/$',
  path: '/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/build-an-app': typeof DocsBuildAnAppRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/build-an-app': typeof DocsBuildAnAppRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/blogs': typeof BlogsIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/build-an-app': typeof DocsBuildAnAppRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/support'
    | '/api/search'
    | '/blogs/$'
    | '/docs/$'
    | '/docs/build-an-app'
    | '/docs/quickstart'
    | '/blogs/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/support'
    | '/api/search'
    | '/blogs/$'
    | '/docs/$'
    | '/docs/build-an-app'
    | '/docs/quickstart'
    | '/blogs'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/support'
    | '/api/search'
    | '/blogs/$'
    | '/docs/$'
    | '/docs/build-an-app'
    | '/docs/quickstart'
    | '/blogs/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogsSplatRoute: typeof BlogsSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsBuildAnAppRoute: typeof DocsBuildAnAppRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/build-an-app': {
      id: '/docs/build-an-app'
      path: '/docs/build-an-app'
      fullPath: '/docs/build-an-app'
      preLoaderRoute: typeof DocsBuildAnAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$': {
      id: '/blogs/$'
      path: '/blogs/$'
      fullPath: '/blogs/$'
      preLoaderRoute: typeof BlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogsSplatRoute: BlogsSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsBuildAnAppRoute: DocsBuildAnAppRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
